In [27]:
import numpy as np 
import pandas as pd

In [28]:
# Loading Data

In [29]:
df = pd.read_csv(r"anime.csv")    #.csv file load korar syntax holo pd.read_csv(r"file_name")

In [30]:
df.head()   # .head() diye prothom 5 ta data dekha hoy.

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [31]:
# Make a new column for episode count

In [32]:
df.loc[2, "Title"]

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [33]:
# def extract_episode(txt):
#     check = False
#     data = ""
#     for i in txt:
#         if i == ")":    i = Sennen Kessen-henTV (13 eps
#             check = False
#             return data    "Sennen Kessen-henTV (" 
#         if check == True:
#             data = data + i
#         if i == "(":    ( found
#             check = True

In [34]:
# def extract_episode(txt):    # ekhane anime gular episode sonkhake alada kora hoyecche.
#     check = False
#     data = ""
#     for i in txt:
#         if i == ")":
#             check = False
#             return data
#         if check == True:
#             data = data + i
#         if i == "(":
#             check = True

In [35]:
def extract_episode(txt):    # ekhane anime gular episode sonkhake alada kora hoyecche.
    data = ""
    for i in range(len(txt)):
        if txt[i] == "(":
            for j in range(i+1, i+3): 
                data += txt[j]
            return data

In [36]:
df["Episods"] = df['Title'].apply(extract_episode)  # prothome to function er madhome kontar kono episode choltese oita cound kora hoise 
df                                                    # and then tader ke notun ekta column er modhe rakha hoise jetar name "Episode"

    Rank                                              Title  Score Episods
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10      64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07      24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06      13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06      51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05      10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04      51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04      1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04      14
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04      13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03      13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03      2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02      11
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99      13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99      13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98      12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94      20
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94      1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93      22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93      24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91      25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91      1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89      1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88      7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88      14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87      74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84      1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84      1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83      12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83      1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82      24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82      23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81      12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81      26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80      13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80      16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79      11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79      1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79      11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78      10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78      1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77      26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77      12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76      75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75      26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75      26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74      24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73      10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72      12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71      12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71      4

In [37]:
df.loc[6]["Episods"]      # eita bortomane string e ase

'1 '

In [38]:
df["Episods"] = df["Episods"].astype(int)

In [39]:
df.loc[6]["Episods"]

np.int64(1)

In [40]:
df

    Rank                                              Title  Score  Episods
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04       51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04        1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04       14
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04       13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03       13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03        2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02       11
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99       13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99       13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98       12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94       20
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94        1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93       22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93       24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91       25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91        1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89        1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88        7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88       14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87       74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84        1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84        1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83       12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83        1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82       24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82       23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81       12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81       26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80       13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80       16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79       11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79        1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79       11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78       10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78        1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77       26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77       12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76       75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75       26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75       26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74       24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73       10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72       12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71       12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71        4

In [41]:
# Make a new column for time stamp

In [42]:
df.loc[0]["Title"]

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [43]:
def extract_date(txt): 
    data = "" 
    for i in range(len(txt)): 
        if txt[i] == ")": 
            for j in range(i+1, i+20): 
                data += txt[j]
            return data

In [44]:
df["Date"] = df["Title"].apply(extract_date)

In [45]:
df.head()

,Rank,Title,Score,Episods,Date
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [46]:
# Which anime has the highest score

In [56]:
df[df["Score"] == df["Score"].max()]

,Rank,Title,Score,Episods,Date
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010

In [48]:
# Give me top 5 highest scoring anime

In [49]:
df["Title"].head()    # ekhane value count diyeo kora jaito , but ekhane age thekei sob sorted acche tai just head gulake print kora mane top 5 anime jegula sobcheye beshi score korecche

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: str

In [50]:
# Which anime has the highest episode count

In [54]:
df[df["Episods"] == df["Episods"].max()]

,Rank,Title,Score,Episods,Date
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002

In [57]:
# Animies with top 5 episods count

In [64]:
df.sort_values(
    by="Episods",
    ascending=False
).head()

,Rank,Title,Score,Episods,Date
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012

In [ ]:
# Which is the longest running anime

In [69]:
df["Start Date"] = pd.to_datetime(
    df["Date"].str.split(" - ").str[0],      # chatgpt theke newa hoyecche
    format="%b %Y",
    errors="coerce"
)

df["End Date"] = pd.to_datetime(
    df["Date"].str.split(" - ").str[1],
    format="%b %Y",
    errors="coerce"
)

df["Running Months"] = (
    (df["End Date"].dt.year - df["Start Date"].dt.year) * 12
    + df["End Date"].dt.month - df["Start Date"].dt.month
)

df.sort_values(by="Running Months", ascending=False).head(5)

,Rank,Title,Score,Episods,Date,Start Date,End Date,Running Months
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,11,Jan 1988 - Mar 1997,1988-01-01,1997-03-01,110
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,20,Apr 2006 - Mar 2010,2006-04-01,2010-03-01,47
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,14,Oct 2011 - Sep 2014,2011-10-01,2014-09-01,35
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021,2020-04-01,2021-10-01,18
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,2004-04-01,2005-09-01,17